steps:
# Cloning the Git repo
# - name: 'gcr.io/cloud-builders/git'
#   args: ['clone', '']

- name: 'gcr.io/${_GOOGLE_CLOUD_PROJECT}/docker-compose'
  args: ['up', '-d', 'postgres']
- name: 'gcr.io/${_GOOGLE_CLOUD_PROJECT}/docker-compose'
  args: ['up', '-d', 'redis']
- name: 'gcr.io/${_GOOGLE_CLOUD_PROJECT}/docker-compose'
  args: ['run','sentry', 'sentry', 'upgrade']

# Tagging docker images
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'postgres:9.6.1', 'gcr.io/${_GOOGLE_CLOUD_PROJECT}/postgres:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'redis:3.0.7', 'gcr.io/${_GOOGLE_CLOUD_PROJECT}/redis:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'sentry:8.10.0', 'gcr.io/${_GOOGLE_CLOUD_PROJECT}/sentry:latest']

# Pushing docker images to Container registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${_GOOGLE_CLOUD_PROJECT}/postgres:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${_GOOGLE_CLOUD_PROJECT}/redis:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${_GOOGLE_CLOUD_PROJECT}/sentry:latest']

# deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=deployment.yaml
  - --image=gcr.io/${_GOOGLE_CLOUD_PROJECT}/sentry:latest
  env : 
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=sentry-cluster'
substitutions:
  _GOOGLE_CLOUD_PROJECT : doug-s-sandbox
