apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
 {{- with .Values.clickHouse.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
 {{- end }}
  labels:
    {{- include "sentry.clickHouse.labels" . | nindent 4 }}
  name: {{ include "sentry.clickHouse.fullname" . }}