apiVersion: v1
kind: Service
metadata:
 {{- with .Values.clickHouse.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
 {{- end }}
  labels:
    {{- include "sentry.clickHouse.labels" . | nindent 4 }}
  name: "{{ include "sentry.clickHouse.fullname" . }}-headless"
spec:
  ports:
    {{- toYaml .Values.clickHouse.service | nindent 8 }} 
  selector:
    {{- include "sentry.clickHouse.selectorLabels" . | nindent 6 }}
  type: none